# Generated by Django 6.0.3 on 2026-04-14 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='members',
            new_name='Member',
        ),
    ]
