# Generated by Django 6.0.6 on 2026-06-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjapp', '0002_item_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description_ar',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='item',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='item',
            name='description_fr',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='item',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='Item Name'),
        ),
        migrations.AddField(
            model_name='item',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Item Name'),
        ),
        migrations.AddField(
            model_name='item',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='Item Name'),
        ),
    ]
