# Generated by Django 6.0.5 on 2026-05-19 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du produit', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description du produit')),
                ('price', models.DecimalField(decimal_places=2, help_text='Prix en cents', max_digits=10)),
                ('stripe_price_id', models.CharField(help_text='ID du prix Stripe', max_length=255)),
                ('stripe_product_id', models.CharField(blank=True, help_text='ID du produit Stripe', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
            },
        ),
        migrations.CreateModel(
            name='CheckoutSessionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255)),
                ('stripe_checkout_session_id', models.CharField(max_length=255, unique=True)),
                ('stripe_price_id', models.CharField(max_length=255)),
                ('amount_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='eur', max_length=3)),
                ('has_access', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('payment_status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text="L'utilisateur qui a initié le checkout", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sim.product')),
            ],
            options={
                'verbose_name': 'Session de paiement',
                'verbose_name_plural': 'Sessions de paiement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='eur', max_length=3)),
                ('status', models.CharField(max_length=50)),
                ('payment_method', models.CharField(blank=True, max_length=100)),
                ('receipt_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checkout_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sim.checkoutsessionrecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique de paiement',
                'verbose_name_plural': 'Historique des paiements',
                'ordering': ['-created_at'],
            },
        ),
    ]
